run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - whitespace

linters-settings:
  goimports:
    local-prefixes: sigs.k8s.io/prometheus-adapter
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
